import { z } from "zod";

const numberField = z.preprocess(
  (value) =>
    value === "" || value === null || value === undefined ? null : value,
  z.coerce.number().nullable(),
);
const integerField = z.preprocess(
  (value) =>
    value === "" || value === null || value === undefined ? null : value,
  z.coerce.number().int().nullable(),
);
const textField = z.coerce.string();

export const ptmTypes = [
  "acet_K",
  "methyl_K",
  "methyl_R",
  "phos_S",
  "phos_T",
  "phos_Y",
] as const;

export const systemColumns = [
  "ptm_type",
  "protein_name",
  "uniprot_id",
  "site",
  "mod",
  "status",
  "final_flag",
  "site_status",
  "issues",
  "rmsd_type",
  "rmsd_mean_A",
  "rmsd_equil_mean_A",
  "rmsd_equil_std_A",
  "rmsd_max_A",
  "rmsd_slope_A_per_ns",
  "rmsd_max_jump_A",
  "sim_time_ns",
  "n_frames",
  "rg_mean_A",
  "rg_cv_percent",
  "rg_slope_A_per_ns",
  "rmsf_mean_A",
  "rmsf_max_A",
  "rmsf_median_A",
  "n_residues",
  "rmsf_frac_highflex_percent",
  "site_resid",
  "site_rmsd_equil_mean_A",
  "site_rmsd_max_A",
  "site_rmsd_slope_A_per_ns",
  "site_rmsf_mean_A",
  "site_rmsf_ratio_to_median",
  "n_reps",
  "traj_ns_total",
  "rmsf_mean_all_A",
  "rmsf_mean_core_A",
  "n_ca",
  "plddt_mean",
  "plddt_median",
  "plddt_min",
  "plddt_p10",
  "site_plddt",
  "frac_lt70_pct",
  "site_resname",
  "site_is_het",
  "dist_to_nterm",
  "dist_to_cterm",
  "rel_pos_from_nterm",
  "is_terminal_lt10",
  "n_neighbors_8A",
  "n_neighbors_seq_far_8A",
  "burial_class",
  "local_plddt_8A",
  "rmsd_1v2",
  "rmsd_1v3",
  "rmsd_2v3",
  "rmsd_inter_mean",
  "rmsd_inter_max",
  "rmsd_mean_3rep_A",
  "rmsd_equil_mean_3rep_A",
  "rg_mean_3rep_A",
  "sasa_total_mean_nm2",
  "sasa_site_mean_nm2",
  "n_sb_contacts_mean",
  "n_sb_contacts_std",
  "chi1_mean_deg",
  "chi1_circ_std_deg",
  "chi1_dominant_rotamer",
  "chi2_mean_deg",
  "chi2_circ_std_deg",
  "chi2_dominant_rotamer",
  "site_ss_dominant",
  "site_ss_H_pct",
  "site_ss_E_pct",
  "site_ss_C_pct",
  "site_ss_stability",
  "batches",
] as const;

export const integerColumns = [
  "n_frames",
  "n_residues",
  "site_resid",
  "n_reps",
  "n_ca",
  "site_is_het",
  "dist_to_nterm",
  "dist_to_cterm",
  "is_terminal_lt10",
  "n_neighbors_8A",
  "n_neighbors_seq_far_8A",
] as const;

export const numberColumns = [
  "rmsd_mean_A",
  "rmsd_equil_mean_A",
  "rmsd_equil_std_A",
  "rmsd_max_A",
  "rmsd_slope_A_per_ns",
  "rmsd_max_jump_A",
  "sim_time_ns",
  "rg_mean_A",
  "rg_cv_percent",
  "rg_slope_A_per_ns",
  "rmsf_mean_A",
  "rmsf_max_A",
  "rmsf_median_A",
  "rmsf_frac_highflex_percent",
  "site_rmsd_equil_mean_A",
  "site_rmsd_max_A",
  "site_rmsd_slope_A_per_ns",
  "site_rmsf_mean_A",
  "site_rmsf_ratio_to_median",
  "traj_ns_total",
  "rmsf_mean_all_A",
  "rmsf_mean_core_A",
  "plddt_mean",
  "plddt_median",
  "plddt_min",
  "plddt_p10",
  "site_plddt",
  "frac_lt70_pct",
  "rel_pos_from_nterm",
  "local_plddt_8A",
  "rmsd_1v2",
  "rmsd_1v3",
  "rmsd_2v3",
  "rmsd_inter_mean",
  "rmsd_inter_max",
  "rmsd_mean_3rep_A",
  "rmsd_equil_mean_3rep_A",
  "rg_mean_3rep_A",
  "sasa_total_mean_nm2",
  "sasa_site_mean_nm2",
  "n_sb_contacts_mean",
  "n_sb_contacts_std",
  "chi1_mean_deg",
  "chi1_circ_std_deg",
  "chi2_mean_deg",
  "chi2_circ_std_deg",
  "site_ss_H_pct",
  "site_ss_E_pct",
  "site_ss_C_pct",
  "site_ss_stability",
] as const;

export const textColumns = systemColumns.filter(
  (column) =>
    !integerColumns.includes(column as (typeof integerColumns)[number]) &&
    !numberColumns.includes(column as (typeof numberColumns)[number]),
);

export const systemRowSchema = z.object({
  ptm_type: z.enum(ptmTypes),
  protein_name: textField.min(1),
  uniprot_id: textField.min(1),
  site: textField.min(1),
  mod: textField.min(1),
  status: textField,
  final_flag: textField,
  site_status: textField,
  issues: textField,
  rmsd_type: textField,
  rmsd_mean_A: numberField,
  rmsd_equil_mean_A: numberField,
  rmsd_equil_std_A: numberField,
  rmsd_max_A: numberField,
  rmsd_slope_A_per_ns: numberField,
  rmsd_max_jump_A: numberField,
  sim_time_ns: numberField,
  n_frames: integerField,
  rg_mean_A: numberField,
  rg_cv_percent: numberField,
  rg_slope_A_per_ns: numberField,
  rmsf_mean_A: numberField,
  rmsf_max_A: numberField,
  rmsf_median_A: numberField,
  n_residues: integerField,
  rmsf_frac_highflex_percent: numberField,
  site_resid: integerField,
  site_rmsd_equil_mean_A: numberField,
  site_rmsd_max_A: numberField,
  site_rmsd_slope_A_per_ns: numberField,
  site_rmsf_mean_A: numberField,
  site_rmsf_ratio_to_median: numberField,
  n_reps: integerField,
  traj_ns_total: numberField,
  rmsf_mean_all_A: numberField,
  rmsf_mean_core_A: numberField,
  n_ca: integerField,
  plddt_mean: numberField,
  plddt_median: numberField,
  plddt_min: numberField,
  plddt_p10: numberField,
  site_plddt: numberField,
  frac_lt70_pct: numberField,
  site_resname: textField,
  site_is_het: integerField,
  dist_to_nterm: integerField,
  dist_to_cterm: integerField,
  rel_pos_from_nterm: numberField,
  is_terminal_lt10: integerField,
  n_neighbors_8A: integerField,
  n_neighbors_seq_far_8A: integerField,
  burial_class: textField,
  local_plddt_8A: numberField,
  rmsd_1v2: numberField,
  rmsd_1v3: numberField,
  rmsd_2v3: numberField,
  rmsd_inter_mean: numberField,
  rmsd_inter_max: numberField,
  rmsd_mean_3rep_A: numberField,
  rmsd_equil_mean_3rep_A: numberField,
  rg_mean_3rep_A: numberField,
  sasa_total_mean_nm2: numberField,
  sasa_site_mean_nm2: numberField,
  n_sb_contacts_mean: numberField,
  n_sb_contacts_std: numberField,
  chi1_mean_deg: numberField,
  chi1_circ_std_deg: numberField,
  chi1_dominant_rotamer: textField,
  chi2_mean_deg: numberField,
  chi2_circ_std_deg: numberField,
  chi2_dominant_rotamer: textField,
  site_ss_dominant: textField,
  site_ss_H_pct: numberField,
  site_ss_E_pct: numberField,
  site_ss_C_pct: numberField,
  site_ss_stability: numberField,
  batches: textField,
});

export type SystemRow = z.infer<typeof systemRowSchema>;

export type SystemSummary = Pick<
  SystemRow,
  | "ptm_type"
  | "protein_name"
  | "uniprot_id"
  | "site"
  | "mod"
  | "rmsd_equil_mean_A"
  | "rg_mean_A"
  | "rmsf_mean_core_A"
  | "n_residues"
  | "sim_time_ns"
  | "n_reps"
  | "plddt_mean"
  | "site_plddt"
  | "burial_class"
  | "site_ss_dominant"
  | "sasa_site_mean_nm2"
  | "n_sb_contacts_mean"
  | "chi1_dominant_rotamer"
  | "chi2_dominant_rotamer"
  | "rmsd_inter_mean"
  | "rmsd_1v2"
  | "rmsd_1v3"
  | "rmsd_2v3"
>;

export const systemSummarySchema = systemRowSchema.pick({
  ptm_type: true,
  protein_name: true,
  uniprot_id: true,
  site: true,
  mod: true,
  rmsd_equil_mean_A: true,
  rg_mean_A: true,
  rmsf_mean_core_A: true,
  n_residues: true,
  sim_time_ns: true,
  n_reps: true,
  plddt_mean: true,
  site_plddt: true,
  burial_class: true,
  site_ss_dominant: true,
  sasa_site_mean_nm2: true,
  n_sb_contacts_mean: true,
  chi1_dominant_rotamer: true,
  chi2_dominant_rotamer: true,
  rmsd_inter_mean: true,
  rmsd_1v2: true,
  rmsd_1v3: true,
  rmsd_2v3: true,
});
